version: "3.3"
services:
  web:
    build: ./app
    ports:
      - "5000:5000"
    environment:
      host: 'mysql-db'
    restart: always
  mysql-db:
    image: mysql:5.7
    restart: always
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql

    environment:
      MYSQL_DATABASE: 'test'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'usr'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
  # Names our volume
volumes:
  my-db:
